### ISSUE TITLE
videos without title have empty box

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#100]
![screenshot 2018-01-30 16 16 11](https://user-images.githubusercontent.com/2199845/35591722-f4cc905e-05d8-11e8-8ef2-a2f07b5af6f0.png)

**Comment by zebapy** [comment]
@imcbride Looks like this was taken from https://www.middlebury.edu/institute/academics/degree-programs but now there's a video title. Basically `video__body` shouldn't be rendered if there's no title, text, transcript

**Comment by imcbride** [comment]
Fixed in https://github.com/middlebury/drupal8/commit/cb29b405f30b9eff8256cbb4fcb43f7bcb612d79
