### ISSUE TITLE
using text component for profile listing heading has issues

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#101]
Since profile "listings" are just multiple profile components separated by text components used as a heading, the design falls down now that all text paragraphs have significant bottom margin. 

![screenshot 2018-01-30 16 22 43](https://user-images.githubusercontent.com/2199845/35592037-d0abfede-05d9-11e8-8149-df9d01728fa7.png)

**Comment by imcbride** [comment]
The text paragraphs will often just be headings, but they don't necessarily _have_ to be. Editors might choose to include regular paragraphs of text explaining roles or providing generic contact information for departments.

**Comment by zebapy** [comment]
Per discussion, sounds like we'll possibly create a Profile Listing Heading component specifically for this unless an alternative css fix can be done.

**Comment by imcbride** [comment]
Fixed in https://github.com/middlebury/drupal8/commit/5634c9569c0fd70c01d44fe0a5234f77400f502b
