### ISSUE TITLE
Create profile listing pages for staff team pages

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/frontend#104]
I know this isn't front-end per se, but I don't have a great place to track this work.

### Staff profiles to be created
- [x] Admissions/Recruiting: http://www.miis.edu/admissions/contact
- [x] Student Life/International Student Services http://www.miis.edu/student-life/contact
- [x] CACS http://www.miis.edu/careers/contact
- [x] Advancement/Alumni Relations http://www.miis.edu/giving/contact
- [x] Library http://www.miis.edu/academics/library/staff
- [x] Language and Professional Programs http://www.miis.edu/academics/language/programs/team
- [x] CBE – (I think we already have Jason, so everyone else) - Eva might have new photos for them http://centerfortheblueeconomy.org/about/faculty-and-staff/people-staff
- [x] Governance – http://www.miis.edu/about/governance/administration

- [x] Human Resources

**Comment by zebapy** [comment]
A content repo wouldn't be the worst. I've seen repos made just for using issues. Also Project notes without issues can have checkbox lists.

**Comment by kettlestitch** [comment]
I am open to anything. We have no way to track content issues at the moment, so I just created a ticket here. But we need a way to track these somehow. Again, open to anything.

**Comment by imcbride** [comment]
There are also a lot of 3rd party enhancements to Github that add features on top of the project / issue UI that might make this easier for you to track.
