### ISSUE TITLE
Improve display of top right CTA on program pages

### ISSUE THREAD

**Issue by imcbride** [middlebury/frontend#108]
![screen shot 2018-02-02 at 9 48 09 am](https://user-images.githubusercontent.com/662895/35738987-4e284f86-07fe-11e8-9b04-5af482fd2f27.png)

I "fixed?" this in the browser inspector by reducing the padding to 30px and removing flex, but you probably have a better approach.

**Comment by imcbride** [comment]
I always ask for a URL, so I should provide one: https://www.middlebury.edu/institute/academics/degree-programs/international-education-management

**Comment by zebapy** [comment]
Looks like I'm getting an issue with minify/combining media queries (putting these here for reference later)

prod:
![screenshot 2018-02-02 10 42 01](https://user-images.githubusercontent.com/2199845/35741774-a7a10c12-0806-11e8-9365-9a8a77e9787b.png)

dev: 
![screenshot 2018-02-02 10 42 11](https://user-images.githubusercontent.com/2199845/35741777-a9e8e300-0806-11e8-99d2-e0775405d961.png)

**Comment by imcbride** [comment]
Just to call this out: the text that Aaron wants on the page is different than the placeholder text and (importantly) contains bold styling and a line break:

**Application Deadline**
March 30

**Comment by kettlestitch** [comment]
If we need to - we can lose the bold text. The copy was written to the design so hopefully that is still ok.


https://mediawiki.middlebury.edu/wikis/web_redesign/images/3/3c/T03_-_MPA.png

[https://mediawiki.middlebury.edu/wikis/web_redesign/images/3/3c/T03_-_MPA.png]


________________________________
