### ISSUE TITLE
Button text is too long for mobile

### ISSUE THREAD

**Issue by cg923** [middlebury/frontend#111]
As seen here, this button text is so long that it goes off the screen when displayed on mobile.

![screen shot 2018-02-07 at 11 07 18 am](https://user-images.githubusercontent.com/28875167/35936105-2a685a4e-0bf7-11e8-88de-6e2852a53a42.png)

Please feel free to remove if this is already on your radar or is a duplicate issue.

**Comment by zebapy** [comment]
Thanks @cg923 

This was fixed in https://github.com/middlebury/frontend/commit/faedc5ba1065e8ac33cacf90ff63424f78f9e278

@kettlestitch are we even keeping the projects content still? I haven't gotten anything
