### ISSUE TITLE
pagination breaks on mobile

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#112]
![screenshot 2018-02-07 14 36 53](https://user-images.githubusercontent.com/2199845/35937490-5c497378-0c14-11e8-92cd-e83d8f06bfc1.png)

Causes horizontal scroll on small screens.

https://www.middlebury.edu/institute/people

**Comment by zebapy** [comment]
@imcbride is it possible to have a `<li class="pagination__item--active">` wrapping the `.pagination__link--active`?

**Comment by imcbride** [comment]
It should be. Our pager template is almost entirely custom.

https://github.com/middlebury/drupal8/blob/master/themes/custom/institute_theme/templates/navigation/pager.html.twig

**Comment by zebapy** [comment]
Can we have next/previous buttons?

**Comment by imcbride** [comment]
Yes. The default pager in Drupal has these and I can add them to ours.

https://github.com/middlebury/drupal8/blob/master/core/themes/stable/templates/navigation/pager.html.twig
