### ISSUE TITLE
Possible issue with Edge or Java

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/frontend#143]
Possible issue from Rebecca H.
Her info is here: whatsmybrowser.org/b/TK6FPNJ

Of note - she is using Edge 16 and does not have Java installed.

********

HI,
 
I got a new laptop yesterday that defaults to  Bing for search. I put MIIS.edu in the search function and saw this:

Middlebury Institute of International Studies at Monterey
https://www.middlebury.edu/institute
Why the Middlebury Institute? I wanted to work on ocean health and management issues, and the Institute exposed me to innovative ideas and solutions.

·         Academics
The Middlebury Institute offers professional graduate programs, certificate and …
See results only from middlebury.edu

When I click on the link I see this:

 | Can’t connect securely to this pageThis might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.Try this:·         Go back to the last page
-- | --

I get right in when I go through Chrome but I wanted to share what happens through Bing.
 
Have you seen this before?
 
RH

**Comment by imcbride** [comment]
This is a known issue with Sophos and Edge. She should contact the Helpdesk and I'll make sure this gets routed to our security team, which can change her configuration to fix it.
