### ISSUE TITLE
revise event components

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#148]
- [x] remove event-teaser-lite
- [x] revise event-teaser with left aligned date version from Ari
- [x] change event listing page to use table view 
- [x] change event listing links to use page-nav

**Comment by zebapy** [comment]
@imcbride do you want to review this? I think I have all markup changes for events we have been speaking about. https://github.com/middlebury/frontend/pull/149

**Comment by kettlestitch** [comment]
@zebapy did this go out?

**Comment by imcbride** [comment]
Yes, I merged #149 when I deployed the Drupal change.
