### ISSUE TITLE
Component changes for Audio

### ISSUE THREAD

**Issue by imcbride** [middlebury/frontend#157]
- [ ] Add a title field, which will always be an `<h2>`
- [ ] Add a blurb field, which can be wrapped in a `<p>` like other teaser blurbs
- [ ] Add a transcript field, which should appear below the audio player like it does for the video player
- [ ] Investigate whether the audio player can be skinned and how much effort this is
- [ ] Ensure this works with embedded audio from panopto as well as local HTML5 audio

The title and blurb fields are optional. The transcript field is not optional. I don't think we decided whether the blurb appears above or below the player.

**Comment by imcbride** [comment]
Yes, here's an example.

```
<iframe src="https://midd.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=f9b9f6b5-f52c-40f8-962b-db0b6b214532&v=1" width="720" height="405" style="padding: 0px; border: 1px solid #464646;" frameborder="0" allowfullscreen allow="autoplay"></iframe>
```

**Comment by zebapy** [comment]
@kettlestitch Perhaps we should discuss lazy loading panopto player. The main question is what does the UI look like before a play button click like the video component.

**Comment by imcbride** [comment]
The Panopto embed code is the same for audio as it is for video, so a potential workaround for this is to tell the one or two people who want to embed audio from Panopto that they can do so using the Video component.

http://hammer.middlebury.edu/~imcbride/institute/panopto-audio-test

**Comment by zebapy** [comment]
We'll pass on reskinned audio player for time being. #161 should cover everything else.
