### ISSUE TITLE
Related Basic Content paragraph at 4 columns does not work on Program page

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#30]
Because we use the same markup for Related Basic Content paragraph, and in most other areas of the site it is displayed at 4 columns, it does not work on the program page. 

![screenshot 2017-10-05 15 59 22](https://user-images.githubusercontent.com/2199845/31249676-38ca8ff8-a9e6-11e7-8789-7675f3222a87.png)

**Comment by zebapy** [comment]
Ari is reviewing all components like this

**Comment by zebapy** [comment]
@imcbride Is there any way to add a class or modify markup if this type of component is on basic content?

**Comment by imcbride** [comment]
I could add a different wrapper div around it if it's on a Basic Content, Newsroom, Program, or Profile Listing page (the four types which use a right nav).

A little less clean, but I can get the current path where the paragraph is rendered, determine if it's a node, and determine which type of node it is to then modify the actual paragraph markup. I prefer to avoid this approach, where possible, but it would look something like:

```php
$node = \Drupal::request()->attributes->get('node);
$type = $node->getType();

if (in_array($type, ['basic_content', 'newsroom', 'program', 'profile_listing'])) {
  $variables['has_sidebar'] = TRUE;
}
```

There are various reasons why we might not want to rely on the [Request object](https://api.drupal.org/api/drupal/core!lib!Drupal.php/function/Drupal%3A%3Arequest/8.4.x), and philosophically the paragraph object is not _supposed_ to know where it's being rendered, but if a wrapper div won't work, that's the next viable approach.

**Comment by zebapy** [comment]
This was closed by reducing the column count https://github.com/middlebury/frontend/commit/f1ff678c98d26730e140bc6d707b424fa9dc8323#diff-ae2c0dfacea3b0c84a7dd86145f8f08f

part of #75
