### ISSUE TITLE
Quick Links no longer have two title sections

### ISSUE THREAD

**Issue by imcbride** [middlebury/frontend#33]
We decided that if editors want another section of Quick Links, they just add another Quick Links paragraph to the page, so there are no longer two title sections. I've removed the second one from the inner section. You may wish to update the surrounding markup, but it's not strictly necessary.

**Comment by zebapy** [comment]
This should actually be changed so `quick-links__title` is still present. Instead, the surrounding `.section`/`.section__title` should be removed.

https://github.com/middlebury/drupal8/blob/master/themes/custom/institute_theme/templates/paragraphs/paragraph--quick-links.html.twig

**Comment by imcbride** [comment]
Fixed in https://github.com/middlebury/drupal8/commit/4a0a043d1de6154c5b4224970f51b2ef2584b7f2. I've already removed the wrapping container div from the paragraph template, though that can be added back in the node template, as I'm doing for paragraphs on the homepage and top level pages.
