### ISSUE TITLE
create notification bar component for global alerts

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#63]

**Comment by adamfranco** [comment]
Hi @zebapy -- I've just about finished up my work on the alert bar, having created the admin form at https://www.middlebury.edu/institute/admin/config/system/middalert , handled storage, caching, and other details. My only remaining task is to get this bar displaying on a few custom view pages like News, but this should be enough to get you started. 

The variables we have to work with are the alert level (`notice`, `warning`, `emergency`), the alert label (`Notice`, `Warning`, `Emergency`), and the message, which is a block of WYSIWYG HTML that is likely to include links.

Here is the current markup (in [`modules/custom/middlebury_alert/templates/middlebury-alert-message.html.twig`](https://github.com/middlebury/drupal8/blob/master/modules/custom/middlebury_alert/templates/middlebury-alert-message.html.twig)):

    <div class="midd-alert-bar midd-alert-warning">
      <div class="midd-alert-level-label">Warning: </div>
      <div class="midd-alert-message">
        <p>Moose on Campus!</p>
      </div>
    </div>

I can change this markup as desired, though note that the WYSIWYG editor is adding those wrapping `<p>` tags. They may be difficult to reliably remove without breaking a theoretically longer message, so if you can handle the `<p>` spacing via CSS, that would be ideal.

**Comment by zebapy** [comment]
Thanks @adamfranco I'm still waiting on Ari to get to the design task then I'll get to this

**Comment by adamfranco** [comment]
As noted in the meeting. We'll put super basic placeholder CSS in place for now and let nicer design come later. Below is some suggested styles, can you put these in place, @zebapy?

    .midd-alert-bar {
      padding: 10px;
    }
    .midd-alert-level-label {
      float: left;
      padding-right: 10px;
      font-weight: bold;
    }
    .midd-alert-bar p {
     color: black;
    }
    .midd-alert-notice {
      background-color: yellowgreen;
    }
    .midd-alert-warning {
      background-color: orange;
    }
    .midd-alert-emergency {
      background-color: red;
    }
    .midd-alert-emergency .midd-alert-level-label, .midd-alert-emergency p {
      color: white;
    }

**Comment by zebapy** [comment]
@adamfranco I added markup for this and styles since Ari wrapped up the design. Hopefully it's clear what's what from the commit https://github.com/middlebury/frontend/commit/c2d9e55a76929bc0d655582555c804cf3816b17d

**Comment by adamfranco** [comment]
@zebapy Because the message text is coming from a WYSIWYG editor (Blurb HTML) the message will have at least one paragraph tag, maybe multiple. This is why I added-block level elements in the markup [suggested above](https://github.com/middlebury/frontend/issues/63#issuecomment-359021853). Paragraphs don't get handled in your suggested markup or styles.

**Comment by imcbride** [comment]
@adamfranco @zebapy The Blurb HTML text style actually doesn't allow paragraphs for this very reason.

**Comment by adamfranco** [comment]
Strange, the editor adds them...

<img width="511" alt="screen shot 2018-02-09 at 5 47 43 pm" src="https://user-images.githubusercontent.com/25242/36053830-5fed8d12-0dc1-11e8-8b0d-40d0e8f4daa7.png">


```
<div class="midd-alert-bar midd-alert-warning">
  <div class="midd-alert-level-label">Warning: </div>
  <div class="midd-alert-message">
    <p>This is a test of the notification bar.</p>

<p>Another paragraph</p>

  </div>
</div>
```

**Comment by imcbride** [comment]
Yeah, ideally I'd add modification to CKEditor to disable the paragraph on enter for the Blurb HTML WYSIWYG fields. I'll add a post launch task to the Drupal project for that. However, the paragraphs will be stripped from output. Here are the allowed tags for Blurb HTML:

`<a href hreflang> <abbr title> <br> <em> <q> <s> <strong> <sub> <sup> <u>`

**Comment by adamfranco** [comment]
Ah, I see the problem -- I'm not running the entered text through `check_markup($html, $format)` which is what strips the tags. I'll make that change.
