### ISSUE TITLE
If the Description field is empty on an Area of Focus, the menu overlaps the content.

### ISSUE THREAD

**Issue by imcbride** [middlebury/frontend#73]
![screen shot 2017-12-20 at 10 34 54 am](https://user-images.githubusercontent.com/662895/34214799-82707afc-e571-11e7-9012-62079705ed3c.png)

**Comment by zebapy** [comment]
This was closed by https://github.com/middlebury/frontend/commit/6278c7f6210846c16a86b3d8e0f66d2f77516e4a
