### ISSUE TITLE
Profile listings are not an HTML list

### ISSUE THREAD

**Issue by imcbride** [middlebury/frontend#76]
The Profile Listing content type allows the editor to mix-and-match profiles and text in any order or number they wish. This means that the profile list could be composed like:

profile
text
text
profile
profile
profile
text
profile

Because of this, the profiles cannot be contained in an HTML list. This is how they will look in markup. This means there will need to be additional padding on those items to imitate the styles of the list markup.

![screen shot 2018-01-08 at 4 07 57 pm](https://user-images.githubusercontent.com/662895/34692510-71910d10-f48e-11e7-9c8e-0759c4b467cd.png)

**Comment by zebapy** [comment]
@imcbride is it possible to add a class only when the `profile-teaser` is added as a Paragraph? My concern is adding bottom margin to all `profile-teaser` when there are `profile-teaser`s in `profile-explorer` and taxonomy search results pages where each result is in a `li`.

**Comment by imcbride** [comment]
That's a good point. Unfortunately, the profile-teaser is context agnostic, so it doesn't know it's being used in a paragraph or some other type of list. I can add a wrapper around it, so it can be like:

```
<article class="profile-listing">
  <div class="typography"></div>
  <div class="profile-wrapper">
    <div class="profile-teaser"></div>
  </div>
</article>
```

But I don't see that as much better than just using `profile-listing profile-teaser` to identify it.

**Comment by zebapy** [comment]
Is profile listing the only area `profile-teaser` is added manually by the editor?

**Comment by imcbride** [comment]
Currently, yes. Other places use the "speaker" version of profiles when adding them to related content.

**Comment by zebapy** [comment]
Since they are currently only on profile listing, I'm ok with using `profile-listing profile-teaser` selector though I'd prefer to avoid selectors that change styles of components at a page level.
