### ISSUE TITLE
Determine final social media links for footer

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/frontend#77]
Need to finalize the list of social media accounts and links in the global footer of the website.

**Comment by kettlestitch** [comment]
Social media links should be:

Instagram:
https://www.instagram.com/middleburyinstitute/

Facebook:
https://www.facebook.com/middleburyinstitute

Twitter:
https://twitter.com/miis

LinkedIn:
https://www.linkedin.com/school/middlebury-institute-of-international-studies-at-monterey/

Vimeo:
https://vimeo.com/middleburyinstitute


@zebapy should I update the YML file or do I need to do something else. PLUS, we have two new icons here for Instagram and Vimeo.

**Comment by zebapy** [comment]
@kettlestitch You should be able to update this https://github.com/middlebury/frontend/blob/master/src/data/data.yml#L230

We may not have a vimeo icon so may need Ari on that.

**Comment by kettlestitch** [comment]
Do we have an instagram icon? Or will we need that too?

**Comment by zebapy** [comment]
We have instagram
